spring:
  application:
    name: Property Lookup

eureka:
  instance:
    hostname: ${cf_instance_ip:localhost}
    nonSecurePort: ${cf_instance_port:8080}
    metadataMap:
      instanceId: Instance-${instance_index:0}
  client:
    serviceUrl:
      defaultZone: http://service-discovery.192.168.11.11.xip.io/eureka/